-- See design notes in db-design.txt

CREATE TABLE TRAIL_DIFFICULTIES (
	DIFFICULTY_ID		SMALLINT NOT NULL,
	TYPE			VARCHAR2(255 BYTE),
	PRIMARY KEY 		(DIFFICULTY_ID)
);

CREATE TABLE TRAILS (
	ID				INTEGER NOT NULL,
	NAME				VARCHAR2(255 BYTE) NOT NULL,
	ZIPCODE				SMALLINT NOT NULL,
	DIFFICULTY_ID			SMALLINT NOT NULL,
	POLYLINE			VARCHAR2(255 BYTE),
	LARGEDROP			SMALLINT,
	SMALLDROP			SMALLINT,
	WOODRIDE			SMALLINT,
	SKINNY				SMALLINT,
	LARGEJUMP			SMALLINT,
	SMALLJUMP			SMALLINT,
	GAP				SMALLINT,
  	PRIMARY KEY (ID),
	FOREIGN KEY(DIFFICULTY_ID) 	REFERENCES TRAIL_DIFFICULTIES(DIFFICULTY_ID)
);

CREATE SEQUENCE TRAIL_SEQ
	START WITH 	1
	INCREMENT BY 	1
	MINVALUE 	1
	CACHE		10;
