-- See design notes in db-design.txt

CREATE TABLE TRAIL_DIFFICULTIES (
	DIFFICULTY_ID	SMALLINT NOT NULL,
	TYPE			VARCHAR(255 BYTE),
	PRIMARY KEY 	(DIFFICULTY_ID)
);

CREATE TABLE TRAILS (
	ID				INTEGER NOT NULL,
	NAME				VARCHAR(255 BYTE),
	ZIPCODE			SMALLINT,
	DIFFICULTY_ID		SMALLINT,
	LARGEDROP			SMALLINT,
	SMALLDROP			SMALLINT,
	WOODRIDE			SMALLINT,
	SKINNY			SMALLINT,
	LARGEJUMP			SMALLINT,
	SMALLJUMP			SMALLINT,
	GAP				SMALLINT,
  	PRIMARY KEY (ID),
	FOREIGN KEY(DIFFICULTY_ID) 	REFERENCES TRAIL_DIFFICULTIES(DIFFICULTY_ID)
);
