swagger: "2.0"
info:
  version: "1.0"
  description: "API for information on mountain bike trails"
  title: "mtb-trails-api"
  contact:
    email: "wilsonia@oregonstate.edu"
    
tags:
- name: "trails"
  
paths:
  /trails:
    post:
      tags:
      - "trails"
      summary: "Add a new trail"
      operationId: "addTrails"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Trail object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Trail"
      responses:
        200:
          description: "Success"
        204:
          description: "No data provided"
        400:
          description: "Bad request"
        405:
          description: "Invalid input"
        500:
          description: "Internal server error"
        
    get:
      tags:
      - "trails"
      summary: "Get trails by querey parameters"
      operationId: "getTrails"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: "query"
          name: "name"
          description: "Returns trails containing any specified names."
          required: false
          type: "array"
          items: 
            type: "string"
          collectionFormat: "multi"
        - in: "query"
          name: "difficulty"
          description: "Returns trails of any specified difficulties"
          required: false
          type: "array"
          items:
            type: "string"
            enum: 
            - "Green"
            - "Blue"
            - "Black"
            - "Double Black"
          collectionFormat: "multi"
        - in: "query"
          name: "location"
          description: "Returns trails in any specified zip codes"
          required: false
          type: "array"
          items:
            type: "integer"
          collectionFormat: "multi"
        - in: "query"
          name: "smallDrop"
          description: "Returns trails do or do not contain small drops as specified"
          required: false
          type: "boolean"
        - in: "query"
          name: "largeDrop"
          description: "Returns trails do or do not contain large drops as specified"
          required: false
          type: "boolean" 
        - in: "query"
          name: "woodRide"
          description: "Returns trails do or do not contain wood rides as specified"
          required: false
          type: "boolean" 
        - in: "query"
          name: "skinny"
          description: "Returns trails do or do not contain skinnies as specified"
          required: false
          type: "boolean" 
        - in: "query"
          name: "largeJump"
          description: "Returns trails do or do not contain large jumps as specified"
          required: false
          type: "boolean"
        - in: "query"
          name: "smallJump"
          description: "Returns trails do or do not contain small jumps as specified"
          required: false
          type: "boolean" 
        - in: "query"
          name: "gap"
          description: "Returns trails do or do not contain gaps as specified"
          required: false
          type: "boolean"
      responses:
        200:
          description: "Success"
        204:
          description: "No data provided"
        400:
          description: "Bad request"
        405:
          description: "Invalid input"
        500:
          description: "Internal server error"
        
  /trails/{trailID}:
    get:
      tags:
      - "trails"
      summary: "Return trail object by ID"
      operationId: "getTrailById"
      produces:
      - "application/json"
      parameters:
        - name: "trailID"
          in: "path"
          description: "ID of trail to return"
          required: true
          type: "integer"
      responses:
        200:
          description: "Success"
        204:
          description: "No data provided"
        400:
          description: "Bad request"
        404:
          description: "Trail not found"
        405:
          description: "Invalid input"
        500:
          description: "Internal server error"
    put:
      tags:
      - "trails"
      summary: "Update trail object by ID and body data"
      produces:
      - "application/json"
      parameters:
        - name: "trailID"
          in: "path"
          description: "ID of trail to return"
          required: true
          type: "integer"
        - name: "body"
          in: "body"
          description: "Parameters to be updated"
          required: true
          schema:
            $ref: "#/definitions/Trail"
      responses:
       405:
        description: "Invalid input"
        
    delete:
      tags:
      - "trails"
      summary: "Delete trail object by ID"
      parameters:
        - name: "trailID"
          in: "path"
          description: "ID of trail to delete"
          required: true
          type: "integer"
      responses:
        200:
          description: "Success"
        204:
          description: "No data provided"
        400:
          description: "Bad request"
        404:
          description: "Trail not found"
        405:
          description: "Invalid input"
        500:
          description: "Internal server error"
  
definitions:
  Features:
    type: "object"
    properties:
      largeDrop:
        description: "Drops larger than 4 feet"
        type: "boolean"
      smallDrop:
        description: "Drops smaller than 4 feet"
        type: "boolean"
      woodRide:
        description: "Any built wooden feature"
        type: "boolean"
      skinny:
        description: "Any narrow ride at a height"
        type: "boolean"
      largeJump:
        description: "Jumps taller than 4 feet"
        type: "boolean"
      smallJump:
        description: "Jumps shorter than 4 feet"
        type: "boolean"
      gap:
        description: "Mandatory gaps in trail (must be cleared)"
        type: "boolean"
      
  Trail:
    type: "object"
    required:
    - "name"
    - "location"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "Dan's Trail"
      difficulty:
        type: "string"
        enum:
        - "Green"
        - "Blue"
        - "Black"
        - "Double Black"
      features:
        $ref: "#/definitions/Features"
      location:
        description: "Zip code of trail head"
        type: "integer"