swagger: "2.0"
info:
  version: "1.0"
  description: "API for information on mountain bike trails"
  title: "mtb-trails-api"
  contact:
    email: "wilsonia@oregonstate.edu"

tags:
- name: "trails"

consumes:
- "application/json"
produces:
- "application/json"

paths:
  /trails:
    post:
      tags:
      - "trails"
      summary: "Add a new trail"
      operationId: "addTrails"
      parameters:
      - in: "body"
        name: "body"
        description: "Trail object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Trail"
      responses:
        201:
          description: "New trail object created"
          schema:
            $ref: "#/definitions/Trail"
        400:
          description: "Incorrect syntax in request"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"

    get:
      tags:
      - "trails"
      summary: "Get trails by query parameters"
      operationId: "getTrails"
      parameters:
        - in: "query"
          name: "name"
          description: "Returns trails containing any specified names."
          required: false
          type: "array"
          items:
            type: "string"
          collectionFormat: "multi"
        - in: "query"
          name: "difficulty"
          description: "Returns trails of any specified difficulties"
          required: false
          type: "array"
          items:
            type: "string"
            enum:
            - "Green"
            - "Blue"
            - "Black"
            - "Double Black"
          collectionFormat: "multi"
        - in: "query"
          name: "mostDifficult"
          description: "Returns any trails easier than specified difficulty"
          required: false
          type: "string"
          enum:
          - "Green"
          - "Blue"
          - "Black"
          - "Double Black"
        - in: "query"
          name: "leastDifficult"
          description: "Returns any trails harder than specified difficulty"
          required: false
          type: "string"
          enum:
          - "Green"
          - "Blue"
          - "Black"
          - "Double Black"
        - in: "query"
          name: "zipCode"
          description: "Returns trails in any specified zip codes"
          required: false
          type: "array"
          items:
            type: "integer"
          collectionFormat: "multi"
        - in: "query"
          name: "smallDrop"
          description: "Returns trails do or do not contain small drops"
          required: false
          type: "boolean"
        - in: "query"
          name: "largeDrop"
          description: "Returns trails do or do not contain large drops"
          required: false
          type: "boolean"
        - in: "query"
          name: "woodRide"
          description: "Returns trails do or do not contain wood rides"
          required: false
          type: "boolean"
        - in: "query"
          name: "skinny"
          description: "Returns trails do or do not contain skinnies"
          required: false
          type: "boolean"
        - in: "query"
          name: "largeJump"
          description: "Returns trails do or do not contain large jumps"
          required: false
          type: "boolean"
        - in: "query"
          name: "smallJump"
          description: "Returns trails do or do not contain small jumps"
          required: false
          type: "boolean"
        - in: "query"
          name: "gap"
          description: "Returns trails do or do not contain gaps"
          required: false
          type: "boolean"
      responses:
        200:
          description: "Trail object(s) retrieved"
          schema:
            $ref: "#/definitions/Trails"
        400:
          description: "Incorrect syntax in request"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"

  /trails/{trailID}:
    get:
      tags:
      - "trails"
      summary: "Return trail object by ID"
      operationId: "getTrailById"
      parameters:
        - name: "trailID"
          in: "path"
          description: "ID of trail to return"
          required: true
          type: "integer"
      responses:
        200:
          description: "Trail object retrieved"
          schema:
            $ref: "#/definitions/Trail"
        404:
          description: "No trail exists with this ID"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
    put:
      tags:
      - "trails"
      summary: "Update trail object by ID and body data"
      parameters:
        - name: "trailID"
          in: "path"
          description: "ID of trail to return"
          required: true
          type: "integer"
        - name: "body"
          in: "body"
          description: "Parameters to be updated"
          required: true
          schema:
            $ref: "#/definitions/Trail"
      responses:
        200:
          description: "Trail object updated"
          schema:
            $ref: "#/definitions/Trail"
        400:
          description: "Incorrect syntax in request"
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "No trail exists with this ID"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"

    delete:
      tags:
      - "trails"
      summary: "Delete trail object by ID"
      parameters:
        - name: "trailID"
          in: "path"
          description: "ID of trail to delete"
          required: true
          type: "integer"
      responses:
        204:
          description: "Trail object deleted"
        404:
          description: "No trail exists with this ID"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"


definitions:
  Features:
    type: "object"
    required:
    - "name"
    - "zipCode"
    properties:
      name:
        type: "string"
        example: "Dan's Trail"
      zipCode:
        description: "Zip code of trail head"
        type: "integer"
      difficulty:
        type: "string"
        enum:
        - "Green"
        - "Blue"
        - "Black"
        - "Double Black"
      largeDrop:
        description: "Drops larger than 4 feet"
        type: "boolean"
      smallDrop:
        description: "Drops smaller than 4 feet"
        type: "boolean"
      woodRide:
        description: "Any built wooden feature"
        type: "boolean"
      skinny:
        description: "Any narrow ride at a height"
        type: "boolean"
      largeJump:
        description: "Jumps taller than 4 feet"
        type: "boolean"
      smallJump:
        description: "Jumps shorter than 4 feet"
        type: "boolean"
      gap:
        description: "Mandatory gaps in trail (must be cleared)"
        type: "boolean"

  Trail:
    type: "object"
    properties:
      data:
        properties:
          id:
            type: "integer"
            format: "int64"
          type:
            type: "string"
            default: "Trail"
          attributes:
            $ref: "#/definitions/Features"

  Trails:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          properties:
            id:
              type: "integer"
              format: "int64"
            type:
              type: "string"
              default: "Trail"
            attributes:
              $ref: "#/definitions/Features"

  Error:
    properties:
      status:
        type: "integer"
        description: "HTTP status code."
      developerMessage:
        type: "string"
        description: "An error string aimed at developers."
      userMessage:
        type: "string"
        description: "An error string aimed at end users."
      code:
        type: "integer"
        description: "Error code."
      details:
        type: "string"
        description: "A link to further information about the error."
